import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { SEO } from 'common/components/SEO'
import css from './index.module.scss'
import Menu from 'common/components/menu'
import HolographicAnimation from 'common/components/holographic/Holographic'
import HeaderLogo from 'assets/images/header-logo.svg'
import Link from 'common/components/link'
import ScrollDownIcon from 'assets/icons/scroll-down.svg'
import PinIcon from 'assets/icons/pin.svg'

const Home: NextPage = () => {
  return (
    <div>
      <SEO />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={css['scene']}>
        <div className={css['hero']}>
          <Menu />

          <div className="section" id="title-section">
            <div className={css['title-block']}>
              <p className="title bold">
                UX<span style={{ color: '#7D7D7D' }}>AMS/XXX/22</span>
                <br />
                UNCONFERENCE
              </p>
              <HeaderLogo />
            </div>
          </div>

          <div className="section">
            <div className={css['bottom-block']}>
              <div className={css['date-block']}>
                <p className={`${css['date']}`}>APR 18 —</p>
                <p className={css['where']}>
                  Devconnect
                  <span>Amsterdam</span>
                </p>
              </div>
              <div className={css['call-to-action']}>
                <Link href="" className="button sm">
                  Apply
                </Link>

                <Link href="" className="button sm">
                  Add to calendar
                </Link>
              </div>
              <div className={css['location']}>
                <PinIcon />
                <p>
                  Het West-Indisch Hui
                  <br />
                  Herenmarkt 99, 1013 EC Amsterdam, Netherlands
                </p>
              </div>
            </div>
            <div className={css['scroll-to-continue']}>
              <ScrollDownIcon />
              <p>Scroll to continue</p>
            </div>
          </div>

          <div className={css['animated-background']}>
            <HolographicAnimation />
          </div>
        </div>
      </div>

      <div className={css['scene']}>
        <Menu />
        <p>Test</p>
      </div>
    </div>
  )
}

export default Home
